apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apt-cacher-ng
  namespace: apt-cache
  labels:
    app.kubernetes.io/name: apt-cacher-ng
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apt-cacher-ng
