apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apt-cacher-ng
  namespace: apt-cache
  labels:
    app.kubernetes.io/name: apt-cacher-ng
spec:
  serviceName: apt-cacher-ng
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: apt-cacher-ng
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apt-cacher-ng
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: apt-cacher-ng
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 15
      containers:
      - name: apt-cacher-ng
        image: ghcr.io/zinntikumugai/apt-cache-docker:latest
        ports:
        - name: http
          containerPort: 3142
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /acng-report.html
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /acng-report.html
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: cache
          mountPath: /var/cache/apt-cacher-ng
        - name: config
          mountPath: /etc/apt-cacher-ng/acng.conf
          subPath: acng.conf
      volumes:
      - name: config
        configMap:
          name: apt-cacher-ng-config
  volumeClaimTemplates:
  - metadata:
      name: cache
      labels:
        app.kubernetes.io/name: apt-cacher-ng
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: truenas-nfs-csi
      resources:
        requests:
          storage: 300Gi
